filter:
    excluded_paths:
        - 'bin/*'
        - 'test/*'
        - '*.min.js'
        - 'docs/*'
checks:
    php: true
coding_style:
    php:
        spaces:
            around_operators:
                concatenation: true
build: true
